name: qiskitagent
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - datasets>=4.2.0
      - openai>=1.68.2
      - qiskit>=2.2.2
      - qiskit-aer>=0.17.2
      - qiskit-ibm-runtime>=0.43.0
      - python-dotenv>=1.0.0
      - langchain==0.3.23
      - langchain-community==0.3.21
      - langchain-core==0.3.52
      - langchain-openai==0.3.13
      - langchain-text-splitters==0.3.8
      - langchain_huggingface
      - langchain_google_genai
      - langsmith==0.3.19
      - faiss-cpu==1.10.0